Ajustement de l'affichage des images
noesya/osuny pull request #1314
Opened 2023-10-09 15:16 UTC by pabois

2023-10-09 15:32 UTC, SebouChu requested changes

2023-10-09 15:32 UTC, SebouChu commented on app/controllers/media_controller.rb
> +    if @blob.representable?
variable

2023-10-09 15:32 UTC, SebouChu commented on app/services/importers/hash_to_person.rb
> +      return unless @photo.end_with?('.jpg') || @photo.end_with?('.png') || @photo.end_with?('.svg')
`return unless ['.jpg', '.jpeg', '.png', '.svg'].any? { |extension| @photo.end_with?(extension) }`

2023-10-09 15:32 UTC, SebouChu commented on app/views/admin/application/featured_image/_show.html.erb
> -    <% unless about.best_featured_image.attached? %>
t'as oublié de remettre ce bloc

```
<% unless about.best_featured_image.attached? %>
  <p class="small"><%= t('admin.inheritance.sentence_without_link').downcase %></p>
<% end %>
```

2023-10-09 15:32 UTC, SebouChu commented on app/views/admin/communication/blocks/templates/image/_snippet.html.erb
> +<%= kamifusen_tag object, height: 90, alt: '', class: 'me-2' if object %>
on n'appelle pas kamifusen avec une variant directement

2023-10-09 15:32 UTC, SebouChu commented on app/views/admin/communication/websites/agenda/events/_list.html.erb
> +              <%= kamifusen_tag event.featured_image, width: 200 if event.featured_image.attached? %>
width 100

2023-10-09 15:32 UTC, SebouChu commented on app/views/server/application/_top.html.erb
> +            <%= kamifusen_tag current_user.picture, widht: 40, class: 'avatar img-fluid rounded-circle' %>
width: 40, height: 40

attention à la faute à width

2023-10-09 15:32 UTC, SebouChu commented on app/views/admin/communication/blocks/templates/persons/_snippet.html.erb
> +      <%= kamifusen_tag person.best_picture, width: 90, class: 'img-fluid rounded-circle' %>
width: 90, height: 90

2023-10-09 15:32 UTC, SebouChu commented on app/views/admin/layouts/themes/appstack/_top.html.erb
> +            <%= kamifusen_tag current_user.picture, width: 40, class: 'avatar img-fluid rounded-circle' %>
width: 40, height: 40

2023-10-09 15:32 UTC, SebouChu commented on app/views/admin/layouts/themes/pure/_nav.html.erb
> +              <%= kamifusen_tag current_user.picture, width: 100, class: 'image' %>
width: 100, height: 100

2023-10-09 15:32 UTC, arnaudlevy approved these changes

2023-10-09 15:32 UTC, arnaudlevy commented on app/services/importers/hash_to_person.rb
> +      return unless @photo.end_with?('.jpg') || @photo.end_with?('.png') || @photo.end_with?('.svg')
Ce serait quand même mieux d'avoir un endroit où les extensions autorisées sont listées dans un tableau, là c'est pas beau

2023-10-09 15:32 UTC, arnaudlevy commented on app/views/admin/communication/blocks/templates/persons/_snippet.html.erb
> +      <%= kamifusen_tag person.best_picture, width: 90, class: 'img-fluid rounded-circle' %>
carré ?

2023-10-09 15:32 UTC, arnaudlevy commented on app/views/admin/communication/websites/agenda/events/_list.html.erb
> +              <%= kamifusen_tag event.featured_image, width: 200 if event.featured_image.attached? %>
là tu fais à l'envers, si width 100 retina 200 alors width 100

2023-10-09 15:32 UTC, arnaudlevy commented on app/views/admin/layouts/themes/appstack/_top.html.erb
> +            <%= kamifusen_tag current_user.picture, width: 40, class: 'avatar img-fluid rounded-circle' %>
carré

2023-10-09 15:32 UTC, arnaudlevy commented on app/views/admin/layouts/themes/pure/_panel.html.erb
> +  <%= kamifusen_tag image, class: 'img-fluid mb-3', loading: :lazy if image %>
loading lazy inutile, non ?

2023-10-09 15:40 UTC, pabois commented on app/services/importers/hash_to_person.rb
> +      return unless @photo.end_with?('.jpg') || @photo.end_with?('.png') || @photo.end_with?('.svg')
@photo.end_with?(*['.jpg', '.jpeg', '.png', '.svg']) c'est plus joli, non ?

2023-10-09 15:41 UTC, pabois commented on app/views/admin/application/featured_image/_show.html.erb
> -    <% unless about.best_featured_image.attached? %>
non je l'ai enlevé volontairement. Il était dans une condition plus globale if attached?, donc il ne pouvait jamais s'exécuter

2023-10-09 15:47 UTC, SebouChu commented on app/services/importers/hash_to_person.rb
> +      return unless @photo.end_with?('.jpg') || @photo.end_with?('.png') || @photo.end_with?('.svg')
oui

2023-10-09 16:41 UTC, pabois commented on app/services/importers/hash_to_person.rb
> +      return unless @photo.end_with?('.jpg') || @photo.end_with?('.png') || @photo.end_with?('.svg')
j'ai amélioré

2023-10-10 07:34 UTC, arnaudlevy commented on app/services/importers/hash_to_person.rb
> +      return unless @photo.end_with?('.jpg') || @photo.end_with?('.png') || @photo.end_with?('.svg')
Mieux :
```
AUTHORIZED_EXTENSIONS = [
  '.jpg',  
  '.jpeg',
  '.png',
  '.svg'
]
```
``` 
@photo.end_with?(*AUTHORIZED_EXTENSIONS)
```

2023-10-10 07:43 UTC, pabois commented on app/services/importers/hash_to_person.rb
> +      return unless @photo.end_with?('.jpg') || @photo.end_with?('.png') || @photo.end_with?('.svg')
Regarde le code actuel modifié

2023-10-10 10:22 UTC, arnaudlevy commented on app/views/server/application/_top.html.erb
> +            <%= kamifusen_tag current_user.picture, widht: 40, class: 'avatar img-fluid rounded-circle' %>
widht

2023-10-10 10:22 UTC, arnaudlevy commented on app/services/importers/hash_to_person.rb
> +      return unless @photo.end_with?('.jpg') || @photo.end_with?('.png') || @photo.end_with?('.svg')
c'est toujours aussi balourd, non ?

2023-10-10 10:51 UTC, arnaudlevy commented on app/views/server/application/_top.html.erb
> +            <%= kamifusen_tag current_user.picture, widht: 40, class: 'avatar img-fluid rounded-circle' %>
@pabois il faut corriger ça, sauf erreur

2023-10-10 12:56 UTC, SebouChu requested changes

2023-10-10 12:56 UTC, SebouChu commented on config/locales/en.yml
> +  default_images_hint: "5 Mb max, %{formats}"
MB

2023-10-10 13:06 UTC, SebouChu approved these changes

2023-10-10 13:06 UTC, merged