Traductions automatiques avec Libre translate
noesya/osuny pull request #1507
Opened 2023-12-26 15:14 UTC by arnaudlevy

2023-12-26 17:37 UTC, arnaudlevy commented
Le changement de langue avec le select ne fonctionne plus depuis l'audit je crois : 

```
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://example.osuny.org/js/ https://plausible.io https://d2wy8f7a9ursnm.cloudfront.net/v7/ https://cdn.jsdelivr.net/npm/summernote@0.8.20/dist/lang/ 'nonce-93d6d8b931dc79390c9d4068c16f4461'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
```

2023-12-27 15:09 UTC, SebouChu requested changes

2023-12-27 15:09 UTC, SebouChu commented on app/assets/javascripts/admin/commons/translation.js
> +        this.loader.hidden = true;
cette partie-là doit être exécutée quand tous les XHR ont répondu, là ça va rep trop vite

2023-12-27 15:13 UTC, arnaudlevy commented on app/views/admin/application/i18n/_translate_button.html.erb
> +  path = admin_translate_path target: about.language.iso_code,
ah c'est vrai ce serait bien, je fais plutôt une issue

2023-12-27 15:22 UTC, arnaudlevy commented on app/assets/javascripts/admin/commons/translation.js
> +        this.loader.hidden = true;
sauf erreur ils sont synchrones, donc quand on arrive là c'est fini.

2023-12-27 15:29 UTC, SebouChu commented on app/assets/javascripts/admin/commons/translation.js
> +        this.loader.hidden = true;
les xhr c'est pas synchrone, tu send mais derrière ça va exécuter la méthode du onreadystatechange quand c'est fini

2023-12-27 15:30 UTC, SebouChu commented on app/views/admin/application/i18n/_translate_button.html.erb
> +  path = admin_translate_path target: about.language.iso_code,
ok!

2023-12-27 15:30 UTC, SebouChu approved these changes

2023-12-27 15:59 UTC, merged