Localizations des websites
noesya/osuny pull request #1564
Opened 2024-01-22 16:35 UTC by SebouChu

On permet de traduire le nom du site et de paramétrer des socials différents pour chaque langue.

Le website.name du `data/website.yml` n'était pas utilisé, et les socials sont déplacés dans la config des langues en params

2024-01-25 09:57 UTC, pabois requested changes
Il manque les abilities !

2024-01-25 09:57 UTC, pabois commented on app/controllers/admin/communication/websites/localizations_controller.rb
> +  skip_before_action :load_filters
à virer

2024-01-25 09:57 UTC, pabois commented on app/models/communication/website/localization.rb
> +  before_validation :set_university_id
on: :create ?

2024-01-25 09:57 UTC, pabois commented on app/views/admin/communication/websites/configs/default_languages/static.html.erb
> +  title: <%= localization %>
pour le coup je trouve cet appel bizarre.
Je pense qu'il vaut mieux une méthode "calculated_name" dans le modèle, que le to_s renvoie vers ça, et qu'ici on appelle explicitement la nouvelle méthode.
Là c'est un peu trop magique

2024-01-25 09:57 UTC, pabois commented on app/views/admin/communication/websites/configs/default_languages/static.html.erb
> +      ].each do |network|
social (ou social_element) plutôt que network, l'email est pas un network

2024-01-25 09:59 UTC, SebouChu commented on app/views/admin/communication/websites/configs/default_languages/static.html.erb
> +  title: <%= localization %>
okidoki

2024-01-25 20:42 UTC, arnaudlevy reviewed
Pas mal de petites questions.
Très chouette !

2024-01-25 20:42 UTC, arnaudlevy commented on app/controllers/admin/communication/websites/localizations_controller.rb
> +  def load_localization
je me demande si on ne devrait pas les écrire en lazy et pas en before_action

```
def localization
  @localization ||= @website.find_or_create_localization_for(current_website_language)
end
```
(là j'ai pas géré l'authorize, il faudrait)

2024-01-25 20:42 UTC, arnaudlevy commented on app/helpers/admin/communication/website/localizations_helper.rb
> +  def localization_input(f, attribute_name, website)
à cette taille de helper c'est tentant de faire un partial, je sais pas trop

2024-01-25 20:42 UTC, arnaudlevy commented on app/models/communication/extranet.rb
> -#  allow_experiences_modification :boolean          default(TRUE)
pourquoi ça a disparu ça ?

2024-01-25 20:42 UTC, arnaudlevy commented on app/views/admin/communication/websites/_sidebar.html.erb
> +      navigation << {
pas sûr d'ajouter un menu de plus, je me demande si ça devrait pas être un truc dans des settings

2024-01-25 20:42 UTC, arnaudlevy commented on app/views/admin/communication/websites/_sidebar.html.erb
> +      navigation << {
Faut montrer à Denis et Violenn

2024-01-29 13:32 UTC, SebouChu commented on app/models/communication/extranet.rb
> -#  allow_experiences_modification :boolean          default(TRUE)
parce que ça n'existe pas en réalité
<img width="263" alt="image" src="https://github.com/noesya/osuny/assets/7761386/0fdc2feb-0852-46d2-b6cf-c9989d7747c6">

2024-01-29 13:48 UTC, SebouChu commented on app/views/admin/communication/websites/_sidebar.html.erb
> +      navigation << {
pour l'instant comme ça, on verra dans la refonte

2024-01-29 14:49 UTC, pabois approved these changes

2024-01-29 14:49 UTC, merged