Gestion de campus
noesya/osuny pull request #1570
Opened 2024-01-26 08:53 UTC by arnaudlevy

Fix #1566

2024-01-29 11:27 UTC, pabois requested changes

2024-01-29 11:27 UTC, pabois commented on app/models/education/program.rb
> +  include WebsitesLinkable
à remettre par ordre alpha

2024-01-29 11:27 UTC, pabois commented on app/models/education/program.rb
> +  include Sluggable
à remettre par ordre alpha

2024-01-29 11:27 UTC, pabois commented on app/models/education/diploma.rb
> +  include Sluggable
à remettre par ordre alpha

2024-01-29 11:27 UTC, pabois commented on app/models/communication/website/post/category.rb
> +  include Sluggable # We override slug_unavailable? method
à remettre par ordre alpha

2024-01-29 11:27 UTC, pabois commented on app/models/communication/website/post.rb
> +  include Sluggable # We override slug_unavailable? method
à remettre par ordre alpha

2024-01-29 11:27 UTC, pabois commented on app/models/communication/website/agenda/event.rb
> +  include Sluggable
à remettre par ordre alpha

2024-01-29 11:27 UTC, pabois commented on app/models/communication/website/agenda/category.rb
> +  include Sluggable
à remettre par ordre alpha

2024-01-29 11:27 UTC, pabois commented on app/models/communication/extranet/post.rb
> +  include Sluggable
à remettre par ordre alpha

2024-01-29 11:27 UTC, pabois commented on app/models/education/school.rb
> +  include WebsitesLinkable
à remettre par ordre alpha

2024-01-29 11:27 UTC, pabois commented on app/models/research/hal/publication.rb
> +  include Sluggable
à remettre par ordre alpha

2024-01-29 11:27 UTC, pabois commented on app/models/research/journal.rb
> +  include WebsitesLinkable
à remettre par ordre alpha

2024-01-29 11:27 UTC, pabois commented on app/models/research/journal/paper.rb
> +  include Sluggable
à remettre par ordre alpha

2024-01-29 11:27 UTC, pabois commented on app/models/research/journal/paper/kind.rb
> +  include Sluggable
à remettre par ordre alpha

2024-01-29 11:27 UTC, pabois commented on app/models/research/journal/volume.rb
> +  include Sluggable
à remettre par ordre alpha

2024-01-29 11:27 UTC, pabois commented on app/models/research/laboratory.rb
> +  include WebsitesLinkable
à remettre par ordre alpha

2024-01-29 11:27 UTC, pabois commented on app/models/university.rb
>    include WithPeopleAndOrganizations
à remettre par ordre alpha

2024-01-29 11:27 UTC, pabois commented on app/models/university/organization.rb
> +  include Sluggable
à remettre par ordre alpha

2024-01-29 11:27 UTC, pabois commented on app/models/university/person.rb
> +  include Sluggable
à remettre par ordre alpha

2024-01-29 11:27 UTC, pabois commented on app/views/admin/administration/locations/_form.html.erb
> +      <%= f.association :schools, as: :check_boxes %>
il va falloir un ordre

2024-01-29 11:27 UTC, pabois commented on app/views/admin/administration/locations/_form.html.erb
> +      <%= f.association :programs, as: :check_boxes %>
il va falloir un ordre (l'arbre ?)

2024-01-29 11:27 UTC, pabois commented on app/views/admin/administration/locations/_form.html.erb
> +      <%= f.association :programs, as: :check_boxes %>
<%= f.association :programs,
                          as: :check_boxes,
                          collection: collection_tree(current_university.education_programs),
                          label_method: ->(p) { sanitize p[:label] },
                          value_method: ->(p) { p[:id] } %>

2024-01-30 07:05 UTC, arnaudlevy commented on app/views/admin/administration/locations/_form.html.erb
> +      <%= f.association :schools, as: :check_boxes %>
et surtout un scope sur l'university!
C'est fait.

2024-01-30 08:41 UTC, pabois approved these changes

2024-01-30 10:07 UTC, merged