Summernote paste is back... harder stronger faster smarter
noesya/osuny pull request #1572
Opened 2024-01-26 12:45 UTC by pabois

close #1541 

en préparation de #1442

2024-01-26 13:02 UTC, arnaudlevy commented
Ha ha ha mais on avait pas conclu que c'était inutile parce que sanitized après ?

2024-01-26 13:05 UTC, pabois commented
en fait ca permet d'avoir dans ton éditeur au moment du paste quelque chose qui ressemble à ce que tu auras après avoir sauvé et rechargé.
De plus ça permet de faire plus fin que le sanitizer (par exemple dans la blocs de crédits où on a juste droit à des liens ça veille a tout virer sauf les <a>.
En gros j'établis pour chaque config une whitelist des tags tolérés correspondant aux boutons qu'on a mis dans la config concernée, et je coupe le reste.

2024-01-29 08:01 UTC, arnaudlevy requested changes
C'est certainement très bien, mais c'est incompréhensible et ça devrait être dans un plugin externe je crois

2024-01-29 08:01 UTC, arnaudlevy commented on app/assets/javascripts/application/plugins/summernote.js
> +            .replace(/( class=(")?Mso[a-zA-Z]+(")?)/g, ' ')
il faut de la doc pour toutes ces lignes, c'est incompréhensible

2024-01-29 09:52 UTC, SebouChu approved these changes

2024-01-29 09:53 UTC, merged