Gestion correcte des bodyclass
noesya/osuny pull request #1634
Opened 2024-02-16 10:54 UTC by arnaudlevy

L'héritage de bodyclass est différencié.

| Contexte | Avant | Après |
| - | - | - |
| Page ayant la bodyclass `test` | `test` | `test` | 
| Page dont un ancêtre a la bodyclass `test` | `test` | `ancestor-test` |

2024-02-19 08:39 UTC, pabois commented
ATTENTION : pour mettre en prod ça il faut que le thème soit prêt, puisque les pages héritées n'auront plus la bodyclass actuelle

2024-03-06 15:19 UTC, SebouChu requested changes

2024-03-06 15:19 UTC, SebouChu commented on app/models/communication/website/page.rb
> +    bodyclass.present?  ? bodyclass
c'est pas ça plutôt ?

```
def inherited_bodyclass
  parent&.best_bodyclass
end
```

2024-03-06 15:34 UTC, arnaudlevy commented on app/models/communication/website/page.rb
> +    bodyclass.present?  ? bodyclass
entre les 2 :)
```
parent&.inherited_bodyclass
```

2024-03-06 15:41 UTC, SebouChu approved these changes

2024-03-06 15:42 UTC, merged