Ajout d'un bloc campus et d'un layout pour le bloc formations
noesya/osuny pull request #1654
Opened 2024-02-21 06:17 UTC by arnaudlevy

2024-02-26 08:49 UTC, SebouChu requested changes

2024-02-26 08:49 UTC, SebouChu commented on app/models/communication/block/template/campu.rb
> +class Communication::Block::Template::Campu < Communication::Block::Template::Base
Location plutôt que Campu

2024-02-26 08:49 UTC, SebouChu commented on app/models/communication/block.rb
> +    campus: 3200,
locations

2024-02-26 08:49 UTC, SebouChu commented on app/models/communication/block.rb
> +    references: [:pages, :posts, :persons, :organizations, :agenda, :programs, :campus],
locations

2024-02-26 08:49 UTC, SebouChu commented on app/models/communication/block/template/campu/element.rb
> +class Communication::Block::Template::Campu::Element < Communication::Block::Template::Base
Location::Element

2024-02-26 08:49 UTC, SebouChu commented on app/views/admin/communication/blocks/templates/campus/_edit.html.erb
locations/_edit.html.erb

2024-02-26 08:49 UTC, SebouChu commented on app/views/admin/communication/blocks/templates/campus/_show.html.erb
locations/_show.html.erb

2024-02-26 08:49 UTC, SebouChu commented on app/views/admin/communication/blocks/templates/campus/_show.html.erb
> +class_name = "block block-campus"
block-locations

2024-02-26 08:49 UTC, SebouChu commented on app/views/admin/communication/blocks/templates/campus/_snippet.html.erb
locations/_snippet.html.erb

2024-02-26 08:49 UTC, SebouChu commented on app/views/admin/communication/blocks/templates/campus/_static.html.erb
> +<% next unless element.program %>
next unless element.location

2024-02-26 08:49 UTC, SebouChu commented on app/views/admin/communication/blocks/templates/campus/_static.html.erb
> +        - path: "<%= element.program.path %>"
- slug: "<%= element.location.slug %>"

2024-02-26 08:49 UTC, SebouChu commented on config/locales/communication/contents/en.yml
> +          campus:
locations

2024-02-26 08:49 UTC, SebouChu commented on config/locales/communication/contents/en.yml
> +          sound:
lignes 490 et 491 à supprimer (sound et sound.description), trads déjà en-dessous

2024-02-26 08:49 UTC, SebouChu commented on config/locales/communication/contents/en.yml
> +          campus: Campus
locations

2024-02-26 08:49 UTC, SebouChu commented on config/locales/communication/contents/fr.yml
> +          campus:
locations

2024-02-26 08:49 UTC, SebouChu commented on config/locales/communication/contents/fr.yml
> +          campus: Campus
locations

2024-02-26 16:51 UTC, SebouChu requested changes

2024-02-26 16:51 UTC, SebouChu commented on app/models/communication/block.rb
> +    locations: 3200,
ordre alpha

2024-02-26 16:51 UTC, SebouChu commented on app/models/communication/block/template/location.rb
> +    website.present? && website.administration_locations.any?
website.present? && available_locations.any?

2024-02-26 16:51 UTC, SebouChu commented on app/views/admin/communication/blocks/templates/locations/_edit.html.erb
> +          v-on:click="data.elements.splice(data.elements.indexOf(page), 1)"
`data.elements.indexOf(element)` (et à changer également dans programs/_edit.html.erb, testimonials/_edit.html.erb)

Ou à voir si on peut faire juste `data.elements.splice(index, 1)` comme dans contact/_edit.html.erb et datatable/_edit.html.erb

2024-02-26 16:51 UTC, SebouChu commented on app/views/admin/communication/blocks/templates/locations/_show.html.erb
> +class_name = "block block-campus"
block-locations

2024-02-26 16:51 UTC, SebouChu commented on app/views/admin/communication/blocks/templates/locations/_static.html.erb
> +        - path: "<%= element.location.slug %>"
donc `- path:` et pas `- slug:` comme les orgas ?

2024-02-27 08:05 UTC, arnaudlevy commented on app/views/admin/communication/blocks/templates/locations/_static.html.erb
> +        - path: "<%= element.location.slug %>"
si, t'as raison, slug

2024-02-27 09:17 UTC, SebouChu approved these changes

2024-02-27 09:23 UTC, merged